data:
  name: 'Darcy'
  datapath: '/mnt/md1/zongyi/piececonst_r421_N1024_smooth1.mat'
  total_num: 1024
  offset: 0
  n_sample: 1000
  nx: 421
  sub: 7
  pde_sub: 2

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  fc_dim: 128
  act: gelu

train:
  batchsize: 20
  epochs: 300
  milestones: [100, 150, 200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'darcy-FDM'
  save_name: 'darcy-pretrain-pino.pt'

log:
  project: 'PINO-Darcy-pretrain'
  group: 'gelu-pino'
  entity: hzzheng-pino


